# Generated by Django 4.2.11 on 2024-10-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(max_length=25)),
                ('series', models.TextField()),
                ('made_in', models.CharField(max_length=55)),
                ('production_date', models.DateField()),
                ('technical_details', models.TextField()),
            ],
        ),
    ]
